create table if not exists jobs (
  id bigint generated by default as identity primary key,
  name text,
  designer text,
  details text,
  status text,
  invoice text,
  email text,
  amount numeric,
  payment text,
  due_date date,
  priority text,
  drive_link text,
  created_at timestamptz default now()
);
